name: Publish Docker image
on:
  push:
    branches:
      - "master"
      - "cb-gha-docker-build-caching"
    tags:
      - "*"
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "test/"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'valhalla' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "##[set-output name=tag;]${GITHUB_REF#refs/tags/}"
        id: extract_tag
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push latest
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/valhalla/valhalla:${{ steps.extract_tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/valhalla/valhalla:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Try it out (TODO remove me)
        if: github.ref == 'refs/heads/cb-gha-docker-build-caching'
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/valhalla/valhalla:debug-action
          cache-from: type=gha
          cache-to: type=gha,mode=max
